name: Test And Build
on:
  push:
    branches:
      - feature
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-test-utils
  PJ_BRANCH: feature
  PJ_VERSION: 0.6-SNAPSHOT
jobs:
  unit-test_toposoid-test-utils:
    runs-on: self-hosted
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            docker rm --force $(docker ps -a -q) > /dev/null 2>&1 && :
            docker rmi --force ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker images
            docker system prune -f
            docker volume prune -f
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            docker compose -f docker-compose-workflow.yml up -d ${{ env.PJ_REPO }}
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test:headerCheck"
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt compile"
            docker compose -f docker-compose-workflow.yml up -d neo4j
            docker compose -f docker-compose-workflow.yml up -d sentence-weaviate
            docker compose -f docker-compose-workflow.yml up -d data-accessor-sentence-weaviate-web
            docker compose -f docker-compose-workflow.yml up -d image-weaviate
            docker compose -f docker-compose-workflow.yml up -d data-accessor-image-weaviate-web
            docker compose -f docker-compose-workflow.yml up -d non-sentence-weaviate
            docker compose -f docker-compose-workflow.yml up -d data-accessor-non-sentence-weaviate-web
            docker compose -f docker-compose-workflow.yml up -d toposoid-contents-admin-web
            docker compose -f docker-compose-workflow.yml up -d toposoid-common-image-recognition-web          
            docker compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-japanese-web
            docker compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-japanese-web
            docker compose -f docker-compose-workflow.yml up -d data-accessor-neo4j-web
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST http://localhost:7474
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST -H "Content-Type: application/json" -d '{"sentence": "これはテストです。"}' http://localhost:9006/getFeatureVector
            sleep 60
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*JapaneseTest'"
            docker compose -f docker-compose-workflow.yml rm -fsv toposoid-common-nlp-japanese-web
            docker compose -f docker-compose-workflow.yml rm -fsv toposoid-sentence-parser-japanese-web
            docker compose -f docker-compose-workflow.yml up -d corenlp
            docker compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-english-web
            docker compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-english-web
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST  -d 'Life is beautiful.' http://localhost:9000
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST -H "Content-Type: application/json" -d '{"sentence": "This is a test"}' http://localhost:9008/getFeatureVector
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*EnglishTest'"
            docker rm --force $(docker ps -a -q) > /dev/null 2>&1 && :
            docker rmi --force ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
