name: Test And Build
on:
  push:
    branches:
      - feature
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-test-utils
  PJ_BRANCH: feature
  PJ_VERSION: 0.7-SNAPSHOT
jobs:
  unit-test_toposoid-test-utils-amd64:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            docker rm --force $(docker ps -a -q) > /dev/null 2>&1 && :
            docker rmi --force ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-scala-lib:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-contents-admin-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-file-upload-facade-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-sentence-parser-japanese-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-sentence-parser-english-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-common-image-recognition-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/toposoid-common-table-recognition-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/data-accessor-mysql-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/data-accessor-neo4j-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
            docker rmi --force toposoid/data-accessor-weaviate-web:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :          
            docker images
            docker system prune -f
            docker volume prune -f
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --no-cache=true --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow --no-cache .
            docker compose -f docker-compose-workflow.yml up -d
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST http://localhost:7474
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST -H "Content-Type: application/json" -H "X_TOPOSOID_TRANSVERSAL_STATE: {'userId':'test-user', 'username':'guest', 'roleId':0, 'csrfToken':''}" -d '{"sentence": "これはテストです。"}' http://localhost:9006/getFeatureVector
            for i in {1..10}; do echo "PING" | nc -w 5 localhost 3310 | grep -q "PONG" && { echo "OK!"; break; } || { echo "NG ($i/10) RETRY..."; sleep 2; [ $i -eq 10 ] && exit 1; }; done
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test:headerCheck"
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt compile"             
            sleep 60
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*JapaneseTest'"
            docker compose -f docker-compose-workflow.yml rm -fsv toposoid-common-nlp-japanese-web
            docker compose -f docker-compose-workflow.yml rm -fsv toposoid-sentence-parser-japanese-web
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST  -d 'Life is beautiful.' http://localhost:9000
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST -H "Content-Type: application/json" -H "X_TOPOSOID_TRANSVERSAL_STATE: {'userId':'test-user', 'username':'guest', 'roleId':0, 'csrfToken':''}" -d '{"sentence": "This is a test"}' http://localhost:9008/getFeatureVector
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*EnglishTest'"
            docker rm --force $(docker ps -a -q) > /dev/null 2>&1 && :
            docker rmi --force ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}> /dev/null 2>&1 && :
